[package]
name = "ngs_chat_bots"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-std = "1.13.2"
iced = { version = "0.14.0", features = ["debug", "tokio"] }
rand = "0.9.2"
rfd = "0.17.2"
